#!/bin/bash

# Enable the notebook extension
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter nbextension enable --py --sys-prefix bqplot

# Install a JupyterLab extension for widgets
jupyter labextension install @jupyter-widgets/jupyterlab-manager