#!/bin/bash

# Enable the notebook extensions for widgets
jupyter nbextension enable --py widgetsnbextension --sys-prefix

# Install JavaScript dependencies for ipywidgets
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter lab build --minimize=False 